--- 
- name: installs fail2ban on ansible hosts
  hosts: website
  become: yes
  tasks:
  
  - name: install yum fail2ban packages
    ansible.builtin.command: yum install fail2ban -y

  - name: override the basic fail2ban configuration with .local file
    copy:
      src: jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
