- name: Check for missing Linux patches
  hosts: 172.17.14.101
  become: yes
  tasks:
    - name: Check available updates from yum
      yum:
        list: updates
      register: yum_updates

    - name: Display missing patches
      debug:
        msg: "Available updates: {{ yum_updates.results | map(attribute='name') | list }}"
